            - name: Upload a Build Artifact
  uses: actions/upload-artifact@v6.0.0
  with:
    
    name: 
    
    path: 
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: 
   
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: 

    compression-level: 

    overwrite:

    include-hidden-files: 
          
